### ISSUE TITLE
Staging error when deploying node.js application

### ISSUE THREAD

**Issue by chbussler** [yudai/cf_nise_installer#39]
Hi,

after the installation of CF with NICE went fine, I tried to push a node.js application. I am getting this error:

```
CFoundry::StackNotFound: 250003: The stack could not be found: The requested app stack lucid64 is not available on this system.
```

The manifest file looks like this:

```

---
applications:
- name: foo
  memory: 256M
  instances: 1
  host: foo
  domain: amecheapp.com
  path: .
  command: node index.js
  buildpack: https://github.com/cloudfoundry/heroku-buildpack-nodejs.git
```

I tried a lot of variations (like not defining a build pack, or use the original domain after installation, installing node manually on the CF system, etc.), but every time I am getting above error. 

When asking for the logs, I get this:

```
192:foo christoph$ cf logs foo
Using manifest file manifest.yml

CFoundry::NotStaged: 170002: App has not finished staging
192:foo christoph$ 
```

Does anybody have an idea/hunch what the error could be? I'll dig more into logs, but maybe somebody came across this situation before.

Thanks,

Christoph
